### ISSUE TITLE
FIFO algorithm bugs

### ISSUE THREAD

**Issue by huoying7080** [coflow/coflowsim#1]
1. line 144 in CoflowSimulator.jar
   
   if reducer transfer 0 bytes in a rack and other task's rate is 100% in the rack, it should not return -1.
2. not reset each flow's rate in function "updateRatesDynamicAlpha"
   
   if not reset flow rate and job's currentAlpha is -1, the "Work conservation" will add free rate to some flow many times and flow rate will exceed link rate.

**Comment by mosharaf** [comment]
Can you please submit a pull request?
